# Generated by Django 6.1.1 on 2026-09-17 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_like_count_remove_video_rating_likevide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingvideo',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
