# Generated by Django 6.1.1 on 2026-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_ratingvideo_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='required_plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze'),
            preserve_default=False,
        ),
    ]
