# Generated by Django 6.1.1 on 2026-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactin',
            name='authority',
            field=models.CharField(default='121212121212121'),
        ),
        migrations.AddField(
            model_name='transactin',
            name='card_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactin',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
