# Generated by Django 6.1.1 on 2026-09-19 13:52

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transactin_authority_transactin_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='end_time',
            field=models.DateTimeField(default=users.models.default_end_time),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plans',
            name='plane_name',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')]),
        ),
    ]
